# -*- coding: utf-8 -*-
"""data_preparation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y0QJXplfGS233cwmvc0VubezWBIDygZK
"""

import pandas as pd

def load_data(filepath):
    data = pd.read_csv(filepath)
    return data

def prepare_data(data):
    train = data.drop(['job', 'marital', 'education', 'contact', 'month', 'poutcome', 'default',
                       'balance', 'housing', 'loan', 'contact', 'month', 'duration', 'pdays',
                       'previous', 'poutcome'], axis=1)
    train['y'].replace({'no': 0, 'yes': 1}, inplace=True)
    X = train.drop(['y'], axis=1)
    Y = train['y']
    return X.T.values, Y.values.reshape(1, Y.size)