# -*- coding: utf-8 -*-
"""utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y0QJXplfGS233cwmvc0VubezWBIDygZK
"""

import numpy as np
from model import forward_propagation

def predict(parameters, X):
    results = forward_propagation(X, parameters)
    predictions = np.around(results['A3'])
    return predictions

def calculate_accuracy(predictions, Y):
    accuracy = float((np.dot(Y, predictions.T) + np.dot(1 - Y, 1 - predictions.T)) / float(Y.size) * 100)
    return accuracy